version: '3.8'
services:
  extranet-db:
    image: mysql
    env_file:
      - .env
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${EXTRANETDB}
    ports:
      - 3307:3306
      - 33070:33060
    volumes:
      - ./extranet-db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - extranet-db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3002:80
    networks:
      - app_network
    volumes:
      - ./client:/usr/src/app:rw

  server:
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5002:5002
    environment:
      - DB_HOST=extranet-db
      - DB_NAME=extranet
      - DB_PASSWORD=rDT5NLbc2&oE
      - DB_USER=extranet
      - DB_PORT=3306
    networks:
      - app_network
    depends_on:
      - extranet-db
    links:
      - extranet-db
    volumes:
      - ./server:/usr/src/app:rw

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_client.conf:/etc/nginx/conf.d
      - ./nginx_server.conf:/etc/nginx/conf.d
    ports:
      - "8085:80"
    depends_on:
      - client
      - server

    networks:
      - app_network

volumes:
  extranet-db:

networks:
  app_network:
    driver: bridge