# Dockerfile server

# Use an official Node.js runtime as a parent image
FROM node:18.16.1-bullseye-slim

# Set the working directory in the container
WORKDIR /server

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install git and npm dependencies
RUN apt-get update && apt-get install -y git && \
    npm install

# Copy the current directory contents into the container at /server
COPY . .

# Specify the command to run on container startup
CMD ["node", "index.js"]